

PERFRAME_TIME = 0.016*2.5  

BATTLE_TYPE_PVE = 0
BATTLE_TYPE_PVP = 1

BATTLE_DEFAULT = 0
BATTLE_PREPARE = 1
BATTLE_START = 2
BATTLE_TURN_STAND_BY = 3
BTTALE_TURN_EXECUTE = 4
BTTALE_TURN_NEXT = 5
BATTLE_END = 6

COMMAND_STATE_PREPARE = 1
COMMAND_STATE_PALY = 2
COMMAND_STATE_STOP = 3

COMMAND_TYPE_ATTACK = 1
COMMAND_TYPE_CAST = 2

TEAM_TYPE_ATTACKER = 1
TEAM_TYPE_DEFENDER = 2

SKILL_SUBTYPE_DEFAULT = 0
SKILL_SUBTYPE_SEAL = 1
SKILL_SUBTYPE_HEAL = 2
SKILL_SUBTYPE_AUXI = 3


ACTOR_LIFE_ALIVE = 0
ACTOR_LIFE_DEAD = 1
ACTOR_LIFE_DEAD_FLY = 2

SKILL_STATE_DEFAULT = 0
SKILL_STATE_START = 1
SKILL_STATE_EXECUTE = 2
SKILL_STATE_END = 3