
== Vertex Post-Processing

Transform Feedback:

[[gl.bind_transform_feedback]]
* _xfb_= *new_transform_feedback*(_target_ ) _NONGL_ +
_xfb~1~_, _xfb~2~_, _..._ = *gen_transform_feedbacks*([_n_ = 1]) +
_xfb~1~_, _xfb~2~_, _..._ = *create_transform_feedbacks*([_n_ = 1]) +
*bind_transform_feedback*(_target_, [_xfb_]) +
*unbind_transform_feedback*(_target_) _NONGL_ +
*delete_transform_feedbacks*(_xfb~1~_, [_xfb~2~_, _..._]) +
[small]#_target_: '_transform feedback_'. +
Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glGenTransformFeedbacks[glGenTransformFeedbacks] -
https://www.khronos.org/opengl/wiki/GLAPI/glBindTransformFeedback[glBindTransformFeedback] -
https://www.khronos.org/opengl/wiki/GLAPI/glDeleteTransformFeedbacks[glDeleteTransformFeedbacks].#

////
[[gl.is_transform_feedback]]
* _boolean_ = *is_transform_feedback*(_xfb_)
////

[[gl.begin_transform_feedback]]
* *begin_transform_feedback*(_primitivemode_) +
*end_transform_feedback*( ) +
*pause_transform_feedback*( ) +
[small]#_primitivemode_: '_triangles_', '_lines_', '_points_'. +
Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glBeginTransformFeedback[glBeginTransformFeedback] -
https://www.khronos.org/opengl/wiki/GLAPI/glEndTransformFeedback[glEndTransformFeedback] -
https://www.khronos.org/opengl/wiki/GLAPI/glPauseTransformFeedback[glPauseTransformFeedback].#

[[gl.transform_feedback_buffer_range]]
* *transform_feedback_buffer_range*(_xfb_, _index_, _buffer_, _offset_, _size_) +
*transform_feedback_buffer_base*(_xfb_, _index_, _buffer_)

[[gl.draw_transform_feedback]]
* *draw_transform_feedback*(_mode_, _xfb_, [_instancecount_]) +
*draw_transform_feedback_stream*(_mode_, _xfb_, _stream_, [_instancecount_]) +
[small]#_mode_: see <<gl.draw_arrays, draw_arrays>>. +
Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glDrawTransformFeedback[glDrawTransformFeedback] -
https://www.khronos.org/opengl/wiki/GLAPI/glDrawTransformFeedbackStream[glDrawTransformFeedbackStream].#

'''

Flatshading:

[[gl.provoking_vertex]]
* *provoking_vertex*(_provokemode_) +
[small]#_provokemode_: '_first vertex convention_', '_last vertex convention_'. +
Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glProvokingVertex[glProvokingVertex].#

'''

Primitive Clipping:

* <<gl.enable, enable/disable/is_enabled>>

[[gl.clip_control]]
* *clip_control*(_origin_, _depth_) +
[small]#_origin_: '_lower left_', '_upper left_'. +
_depth_: '_negative one to one_', '_zero to one_'. +
Rfr: https://www.opengl.org/sdk/docs/man/html/glClipControl.xhtml[glClipControl].#

'''

Controlling Viewport:

[[gl.depth_range]]
* *depth_range*(_near_, _far_, [_index_]) +
*depth_range_array*(_first_, _near~1~_, _far~1~_, [_near~2~_, _far~2~_, _..._]) +
[small]#Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glDepthRange[glDepthRange] -
https://www.khronos.org/opengl/wiki/GLAPI/glDepthRangeIndexed[glDepthRangeIndexed] -
https://www.khronos.org/opengl/wiki/GLAPI/glDepthRangeArray[glDepthRangeArray].#

[[gl.viewport]]
* *viewport*(_x_, _y_, _w_, _h_, [_index_]) +
*viewport_array*(_first_, _x~1~_, _y~1~_, _w~1~_, _h~1~_, [_x~2~_, _y~2~_, _w~2~_, _h~2~_]) +
[small]#Rfr: https://www.khronos.org/opengl/wiki/GLAPI/glViewport[glViewport] -
https://www.khronos.org/opengl/wiki/GLAPI/glViewportIndexed[glViewportIndexed] -
https://www.khronos.org/opengl/wiki/GLAPI/glViewportArray[glViewportArray].#

